# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kinit': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kxmlgui': '@stable'
    'graphics/okular': '@stable'
