#cmakedefine HAVE_VIEWERINTERFACE_H

#ifdef HAVE_VIEWERINTERFACE_H
	#define LIVEPREVIEW_POSSIBLE
#else
	#undef LIVEPREVIEW_POSSIBLE
#endif

#cmakedefine HAVE_POPPLER

#ifdef HAVE_POPPLER
	#define LIBPOPPLER_AVAILABLE
#else
	#undef LIBPOPPLER_AVAILABLE
#endif
