#cmakedefine HAVE_VIEWERINTERFACE_H

#ifdef HAVE_VIEWERINTERFACE_H
	#define LIVEPREVIEW_POSSIBLE
#else
	#undef LIVEPREVIEW_POSSIBLE
#endif

#cmakedefine HAVE_POPPLER_QT4

#ifdef HAVE_POPPLER_QT4
	#define LIBPOPPLER_QT4_AVAILABLE
#else
	#undef LIBPOPPLER_QT4_AVAILABLE
#endif
